version: '3'

services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3030:3030
    volumes:
      - ./:/home/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auth